services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED:-1}
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      HOSTNAME: ${HOSTNAME:-0.0.0.0}
    restart: unless-stopped
